version: "2"
services:
  coordinator:
    image: pollett/docker-riak-cs
    ports:
      - "8080"
      - "8087"
      - "8098"
    environment:
      - DOCKER_RIAK_CS_CLUSTER_SIZE=3
      - DOCKER_RIAK_CS_AUTOMATIC_CLUSTERING=0
    network_mode: bridge
  member:
    image: pollett/docker-riak-cs
    ports:
      - "8080"
      - "8087"
      - "8098"
    links:
      - coordinator:seed
    network_mode: bridge
    depends_on:
      - coordinator
    environment:
      - DOCKER_RIAK_CS_CLUSTER_SIZE=3
      - DOCKER_RIAK_CS_AUTOMATIC_CLUSTERING=1
